[package]
name = "pulsar-jobs"
version = "0.0.0"
edition = "2024"

[dependencies]
bon = "3.8.1"
context = "3.0.0"
parking_lot = "0.12.5"
smallvec = "1.15.1"
log = "0.4.28"
profiling = "1.0.17"
tracy-client = "0.18.3"