[package]
name = "potassium"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/cohaereo/potassium"
authors = ["cohaereo <cohae@cohae.dev>"]
description = "A lean and mean job scheduler"
categories = ["concurrency", "asynchronous"]
keywords = ["fibers", "concurrency", "threading"]

[dependencies]
bon = "3.8.1"
parking_lot = "0.12.5"
smallvec = "1.15.1"
log = "0.4.28"
profiling = { version = "1.0.17" }
num_cpus = "1.17.0"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "job_benchmarks"
harness = false

[profile.profiling]
inherits = "release"
debug = true
